  -- {
  --   -- tab line 
  --   'romgrk/barbar.nvim',
  --   -- dependencies = {
  --   --   'lewis6991/gitsigns.nvim', -- OPTIONAL: for git status
  --   -- },
  --   init = function() vim.g.barbar_auto_setup = false end,
  --   opts = {
  --     -- lazy.nvim will automatically call setup for you. put your options here, anything missing will use the default:
  --     -- animation = true,        -- not sure
  --     -- insert_at_start = true,  -- new tab at start
  --     -- insert_at_end = false,   -- new tab at end
  --     auto_hide = 1,  -- hide when only 1 tab
  --     -- Enables/disable clickable tabs
  --     --  - left-click: go to buffer
  --     --  - middle-click: delete buffer
  --     clickable = true,
  --     -- A buffer to this direction will be focused (if it exists) when closing the current buffer.
  --     -- Valid options are 'left' (the default), 'previous', and 'right'
  --     focus_on_close = 'previous',
  --     -- Hide inactive buffers and file extensions. options are `alternate`, `current`, `visible`, 'extensions', 'inactive'
  --     -- hide = { inactive = true},
  --     -- Enable/disable current/total tabpages indicator (top right corner)
  --     tabpages = true,
  --   },
  -- },
  -- {
  --   -- tabline, tab-line, tab line
  --   'kdheepak/tabline.nvim',
  --   config = function()
  --     require'tabline'.setup {
  --       -- Defaults configuration options
  --       enable = true,
  --       options = {
  --       -- If lualine is installed tabline will use separators configured in lualine by default.
  --       -- These options can be used to override those settings.
  --         section_separators   = {'', ''},
  --         component_separators = {'', ''},
  --         max_bufferline_percent = 66, -- set to nil by default, and it uses vim.o.columns * 2/3
  --         show_tabs_always = false, -- this shows tabs only when there are more than one tab or if the first tab is named
  --         show_devicons = true, -- this shows devicons in buffer section
  --         show_bufnr = false, -- this appends [bufnr] to buffer section,
  --         show_filename_only = false, -- shows base filename only instead of relative path in filename
  --         modified_icon = "+ ", -- change the default modified icon
  --         modified_italic = false, -- set to true by default; this determines whether the filename turns italic if modified
  --         show_tabs_only = false, -- this shows only tabs instead of tabs + buffers
  --       }
  --     }
  --     vim.cmd[[
  --       set guioptions-=e " Use showtabline in gui vim
  --       set sessionoptions+=tabpages,globals " store tabpages and globals in session
  --     ]]
  --   end,
  --   requires = { { 'hoob3rt/lualine.nvim', opt=true }, {'kyazdani42/nvim-web-devicons', opt = true} }
  -- },
